CREATE TABLE IF NOT EXISTS gcn_inbound_notices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notice_uuid CHAR(36) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  source VARCHAR(32) NOT NULL DEFAULT 'kafka',
  topic VARCHAR(255) NOT NULL,
  kafka_partition INT NULL,
  kafka_offset BIGINT NULL,
  kafka_key VARBINARY(512) NULL,
  kafka_timestamp TIMESTAMP(6) NULL,
  content_type VARCHAR(32) NOT NULL DEFAULT 'unknown',
  payload_sha256 CHAR(64) NOT NULL,
  raw_payload LONGTEXT NOT NULL,
  payload_json JSON NULL,
  parse_status VARCHAR(32) NOT NULL DEFAULT 'raw_only',
  validation_status VARCHAR(32) NOT NULL DEFAULT 'not_checked',
  validation_errors JSON NULL,
  schema_url VARCHAR(512) NULL,
  schema_version VARCHAR(64) NULL,
  mission VARCHAR(64) NULL,
  instrument VARCHAR(128) NULL,
  alert_type VARCHAR(64) NULL,
  alert_tense VARCHAR(64) NULL,
  event_name VARCHAR(255) NULL,
  event_ids JSON NULL,
  trigger_time DATETIME(6) NULL,
  alert_datetime DATETIME(6) NULL,
  ra_deg DOUBLE NULL,
  dec_deg DOUBLE NULL,
  ra_dec_error_json JSON NULL,
  healpix_url VARCHAR(1024) NULL,
  classification_json JSON NULL,
  packet_type INT NULL,
  packet_type_name VARCHAR(128) NULL,
  trig_id VARCHAR(128) NULL,
  sequence_num INT NULL,
  isotime DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_inbound_notice_uuid (notice_uuid),
  UNIQUE KEY uq_inbound_kafka_message (topic, kafka_partition, kafka_offset),
  KEY idx_inbound_received_at (received_at),
  KEY idx_inbound_trigger_time (trigger_time),
  KEY idx_inbound_topic_received (topic, received_at),
  KEY idx_inbound_payload_sha256 (payload_sha256)
);

CREATE TABLE IF NOT EXISTS gcn_outbound_notices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  outbox_uuid CHAR(36) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  topic VARCHAR(255) NOT NULL,
  topic_kind VARCHAR(32) NOT NULL DEFAULT 'test',
  payload_json JSON NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  schema_url VARCHAR(512) NULL,
  schema_version VARCHAR(64) NULL,
  validation_status VARCHAR(32) NOT NULL DEFAULT 'not_checked',
  validation_errors JSON NULL,
  mission VARCHAR(64) NULL,
  instrument VARCHAR(128) NULL,
  alert_type VARCHAR(64) NULL,
  alert_tense VARCHAR(64) NULL,
  record_number INT NULL,
  event_name VARCHAR(255) NULL,
  event_ids JSON NULL,
  trigger_time DATETIME(6) NULL,
  alert_datetime DATETIME(6) NULL,
  created_by_dag_id VARCHAR(255) NULL,
  dag_run_id VARCHAR(255) NULL,
  task_id VARCHAR(255) NULL,
  source_pipeline VARCHAR(128) NULL,
  source_product_dir VARCHAR(1024) NULL,
  source_config_path VARCHAR(1024) NULL,
  priority INT NOT NULL DEFAULT 0,
  available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  locked_by VARCHAR(128) NULL,
  locked_at TIMESTAMP(6) NULL,
  attempts_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  last_error TEXT NULL,
  published_at TIMESTAMP(6) NULL,
  idempotency_key VARCHAR(512) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_outbound_outbox_uuid (outbox_uuid),
  UNIQUE KEY uq_outbound_idempotency_key (idempotency_key),
  KEY idx_outbound_status_available (status, available_at),
  KEY idx_outbound_created_at (created_at),
  KEY idx_outbound_payload_sha256 (payload_sha256)
);

CREATE TABLE IF NOT EXISTS gcn_delivery_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  outbound_notice_id BIGINT UNSIGNED NOT NULL,
  attempt_no INT NOT NULL,
  started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  finished_at TIMESTAMP(6) NULL,
  status VARCHAR(32) NOT NULL,
  dry_run BOOLEAN NOT NULL DEFAULT TRUE,
  topic VARCHAR(255) NOT NULL,
  producer_client_label VARCHAR(128) NULL,
  kafka_partition INT NULL,
  kafka_offset BIGINT NULL,
  kafka_metadata_json JSON NULL,
  error_class VARCHAR(255) NULL,
  error_message TEXT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_attempts_outbound_notice_id (outbound_notice_id),
  KEY idx_attempts_started_at (started_at),
  CONSTRAINT fk_attempts_outbound_notice
    FOREIGN KEY (outbound_notice_id)
    REFERENCES gcn_outbound_notices (id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gcn_client_heartbeats (
  component VARCHAR(64) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  status VARCHAR(32) NOT NULL,
  details_json JSON NULL,
  PRIMARY KEY (component)
);

CREATE TABLE IF NOT EXISTS gcn_client_lifecycle_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  event VARCHAR(64) NOT NULL,
  details_json JSON NULL,
  PRIMARY KEY (id),
  KEY idx_lifecycle_created_at (created_at),
  KEY idx_lifecycle_event (event)
);
