

services:
  postgres:
    image: postgres
    container_name: cosi_postgres
    environment:
      - POSTGRES_USER=airflow_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=airflow_db
    #volumes:
     # - ${HOME}/postgres_data:/var/lib/postgresql/data
    #restart: always

  airflow:
    image: airflow:1.1.0
    container_name: cosi_airflow
    environment:
      - AIRFLOW_HOME=/home/gamma/airflow
      - DISPLAY=${DISPLAY}
    volumes:
      - ../dags:/home/gamma//airflow/dags
      - ./airflow.cfg.postgresql:/home/gamma/airflow/airflow.cfg
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/cosiflow:/shared_dir
    ports:
      - "8080:8080"
      - "28888:28888" #jupyter notebook
    #restart: always   
    entrypoint: ["bash", "/home/gamma/entrypoint.sh"]
    #entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data: