# Dockerfile.webgui
FROM python:3.9-slim

# Crea utente gamma
RUN useradd gamma
USER gamma
WORKDIR /home/gamma

# Copia lo script di entrypoint
COPY entrypoint-webgui.sh /home/gamma/entrypoint-webgui.sh

USER root
RUN chmod +x /home/gamma/entrypoint-webgui.sh

# Crea le directory richieste (opzionale)
RUN mkdir -p /home/gamma/workspace/heasarc

# Installa eventuali pacchetti (opzionale)
# RUN pip install flask ...

# ENTRYPOINT ["bash", "/home/gamma/entrypoint-webgui.sh"]